apiVersion: v1
kind: Service
metadata:
  labels:
    service: requested-api-02
  name: requested-api-02
spec:
  ports:
  - name: "5000"
    port: 5000
    targetPort: 5000
    nodePort: 30001
  selector:
    service: requested-api-02
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: requested-api-02
  name: requested-api-02
spec:
  replicas: 1
  selector:
    matchLabels:
      service: requested-api-02
  template:
    metadata:
      labels:
        service: requested-api-02
    spec:
      containers:
      - image: fthiagomedeiros/requested-api-02:latest
        name: requested-api-02
        imagePullPolicy: Always
        env:
        - name: BASE_SERVICE_URL
          valueFrom:
            configMapKeyRef:
              name: request-api-env
              key: BASE_SERVICE_URL
      restartPolicy: Always
